version: '3.8'

services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=86400
      - SE_VNC_NO_PASSWORD=1
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080

  webcam-poc:
    build: .
    container_name: webcam-poc-app
    depends_on:
      - chrome
    volumes:
      - ./src:/app/src
      - ./resources:/app/resources
      - ./output:/app/output
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - USE_REMOTE_SELENIUM=true
      - SELENIUM_REMOTE_URL=http://chrome:4444/wd/hub
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]